from neovim import Nvim
from .prompt import Prompt


class History:
    prompt = ... # type: Prompt

    def __init__(self, prompt: Prompt) -> None: ...

    @property
    def nvim(self) -> Nvim: ...

    def current(self) -> str: ...

    def previous(self) -> str: ...

    def next(self) -> str: ...

    def previous_match(self) -> str: ...

    def next_match(self) -> str: ...
